CREATE TABLE IF NOT EXISTS drawings (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    dtype TINYINT UNSIGNED,
    x1 INT,
    y1 INT,
    x2 INT,
    y2 INT,
    size TINYINT UNSIGNED,
    r TINYINT UNSIGNED,
    g TINYINT UNSIGNED,
    b TINYINT UNSIGNED,
    room VARCHAR(255),
    now DATETIME,
	PRIMARY KEY (id),
    INDEX (now, room)
);

CREATE TABLE IF NOT EXISTS msg (
    id BIGINT AUTO_INCREMENT,
    name VARCHAR(255),
    msg TEXT,
    now DATETIME,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT UNSIGNED AUTO_INCREMENT,
    name VARCHAR(255),
    email VARCHAR(255),
    password VARCHAR(255),
    member TINYINT,
    PRIMARY KEY (id)
);
